### ISSUE TITLE
Example doesn't compile (TestManualllyPdfLayoutMgr)

### ISSUE THREAD

**Issue by eugenevd** [GlenKPeterson/PdfLayoutManager#22]
README.md links to [TestManualllyPdfLayoutMgr.java](https://github.com/GlenKPeterson/PdfLayoutManager/blob/master/src/test/java/TestManualllyPdfLayoutMgr.java) which doesn't compile due to Coord.java being unavailable.

I'm guessing this is due to me using 0.5.3 instead of 0.5.4 ?
README.md lists using 0.5.4 via maven, but this doesn't seem to be available yet on maven repositories...

**Comment by GlenKPeterson** [comment]
I just pulled the latest from the master branch and it built fine with:
```text
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Java version: 1.8.0_191, vendor: Oracle Corporation
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-46-generic", arch: "amd64", family: "unix"
```

I forgot to make a release for 0.5.4, but I've done it now.  Maven Central should show it within the next few hours.  Please confirm if this fixes your issue.

**Comment by eugenevd** [comment]
Thanks @GlenKPeterson that fixed it.
