### ISSUE TITLE
Padding DEFAULT_TEXT_PADDING and NO_PADDING null

### ISSUE THREAD

**Issue by enm260** [GlenKPeterson/PdfLayoutManager#8]
DEFAULT_TEXT_PADDING and NO_PADDING are always null.  Suggest adding not null checks to the of() methods before returning these static values.

**Comment by GlenKPeterson** [comment]
Thanks for reporting this.  I'll try to look at it this weekend, or you can submit a patch and I'll look at that.

**Comment by GlenKPeterson** [comment]
This issue is fixed.  Please upgrade to 0.3.3 to use the patched version.  I appreciate your patch, but I ended up using a different fix, writing a few unit tests, etc.  Thank you very much for reporting this issue!
